# Comment to a new issue.
issuesOpened: >
  If this is a bug report, please upgrade to the latest code and try again:
  
  如果有 bug, 请先更新到最新版试试:
  
  ```
  acme.sh --upgrade
  ```
  
  please also provide the log with `--debug 2`.
  
  同时请提供调试输出 `--debug 2`
  
  see: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
  
  Without `--debug 2` log, your issue will NEVER get replied.
  
  没有调试输出, 你的 issue 不会得到任何解答.


pullRequestOpened: >
  First, NEVER send a PR to `master` branch, it will NEVER be accepted. Please send to the `dev` branch instead.
  
  If this is a PR to support new DNS API or new notification API, please read this guide first:
  https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Dev-Guide
  
  Please check the guide items one by one.
  
  Then add your usage here:
  https://github.com/acmesh-official/acme.sh/wiki/dnsapi
   
  Or some other wiki pages:
  
  https://github.com/acmesh-official/acme.sh/wiki/deployhooks
  
  https://github.com/acmesh-official/acme.sh/wiki/notify
  


